services:
  fastapi_app:
    container_name: virustotal-api
    build:
      context: . 
      dockerfile: Dockerfile  
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=development
    restart: always
